### ISSUE TITLE
Problem with babel-node and long running processes

### ISSUE THREAD

**Issue by raine** [caseywebdev/watchy#13]
When you start a script with `babel-node`, it launches two processes:

```
node ./node_modules/babel/lib/_babel-node index.js
node ./node_modules/.bin/babel-node index.js
```

However, when `watchy` reboots the parent process, the child process is left hanging around, causing issues.

Process list will end up looking like this:

```
node ./node_modules/babel/lib/_babel-node index.js
node ./node_modules/babel/lib/_babel-node index.js
node ./node_modules/babel/lib/_babel-node index.js
...
node ./node_modules/.bin/babel-node index.js
```

~~Is this a bug in babel-node or watchy?~~

edit: Well, definitely doesn't look a bug in watchy.

**Comment by raine** [comment]
https://github.com/foreverjs/forever/issues/687

**Comment by caseywebdev** [comment]
So is babel-node failing to clean up its child process cleanly?

**Comment by raine** [comment]
Yeah, but they all disappear when I `SIGINT` watchy with `^C`.

**Comment by raine** [comment]
And the mind-warping thing is that watchy will keep showing output from the hanging child processes, making you think that changes you make in editor are not always having effect.

**Comment by caseywebdev** [comment]
I think this is a babel problem. I've added an example failing case that doesn't use watchy at all to illustrate the issue. https://github.com/babel/babel/issues/669

Closing for now.

**Comment by caseywebdev** [comment]
@sebmck said:

> `kexec` is just an optional node module now. Install it and this problem will go away.

**Comment by raine** [comment]
I have a similar issue with electron. If you do:

```
"watch": "watchy -w . -- electron main.js"
```

Each time files change, a new electron process is created alongside the old one.

I tested nodemon and it kills the old one fine with this:

```
"watch": "nodemon --exec electron main.js"
```

**Comment by caseywebdev** [comment]
I wonder what signal nodemon is sending. watchy used to have an option to customize the quit signal, which would be helpful in this situation if electron only responds appropriately to SIGINT or SIGQUIT and not SIGTERM.

Could you try using different signals for your case and see if any of those work? You'll want to change [this line](https://github.com/caseywebdev/watchy/blob/e184ff62b1eda2716c6a1ca6b89d4bc70188a09f/lib/pheonix.js#L70) and pass 'SIGINT', 'SIGQUIT', etc to the `kill` method. If one of those works, I'll re-add the option for custom kill signals.

**Comment by raine** [comment]
No change with `SIGINT` or `SIGQUIT`.

**Comment by raine** [comment]
```
git clone git@gist.github.com:6408097ea6eb64c8f45b.git
```

If you want to play around with it.
