### ISSUE TITLE
No SIGTERM sent

### ISSUE THREAD

**Issue by raine** [caseywebdev/watchy#16]
I have an issue where I'm setting up a http server and when watchy restarts the script on changes, the port will be in use suggesting that the previous process is still alive.

So I try listening to `SIGTERM` events in my app to run `server.close()`, but it looks like no `SIGTERM` signal reaches my app, because the log line below is never called.

```js
process.on('SIGTERM', function () {
  console.log('SIGTERM')
});
```

However, if I run my app directly without watchy, I get the event if I `kill -15 pid`.

Is it because I launch my app with a wrapper script that sets up some environment variables?

```sh
#!/usr/bin/env sh

if [ -z "$NODE_ENV" ] || [ "$NODE_ENV" == "development" ]; then
  export blah blha
fi

node server.js
```

```sh
./node_modules/.bin/watchy -w . -- ./bin/run
```

**Comment by raine** [comment]
Looks like I need `exec`!

http://unix.stackexchange.com/a/196053/92659

**Comment by caseywebdev** [comment]
:+1:
