### ISSUE TITLE
Watchy doesn't watch dotfiles, even when you explicitly list them

### ISSUE THREAD

**Issue by emichael** [caseywebdev/watchy#17]
I tried running 

    watchy -w foo/.bar make

and watchy doesn't execute `make` when I update `foo/.bar`.

I'm on version 0.6.2

**Comment by caseywebdev** [comment]
The default `ignore` value is `/\.`, which will ignore all dotfiles. Use `-i` to change the ignore pattern. If you don't want to ignore anything, `^$' should suffice.

```bash
watchy -i '^$' -w foo/.bar make
```

**Comment by emichael** [comment]
Oops, I see. Didn't quite understand what the ignore regex was for. Thanks!

**Comment by caseywebdev** [comment]
No problem
